### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by sabidin802** [egandro/docker-qemu-arm#1]
when i try to install. this is happen.
what it is?... 
can you help me

Closing connection 0
spawn rm -f ./qemukey ./qemukey.pub
spawn ssh-keygen -b 2048 -t rsa -N -f ./qemukey
couldn't execute "ssh-keygen": no such file or directory
while executing
"spawn ssh-keygen -b 2048 -t rsa -N "" -f ./qemukey"
(file "installqemu.expect" line 20)

**Comment by egandro** [comment]
Sure... do you have ssh-keygen i.e. openssl package installed?
