### ISSUE TITLE
 Unable to select packages: dosfstools , e2fsprogs ...

### ISSUE THREAD

**Issue by avto727** [egandro/docker-qemu-arm#11]
Installation crashes with this message
```console
ERROR: unable to select packages:
                   dosfstools (no such package):
                       required by: world[dosfstools]
                  e2fsprogs (no such package):
                        required by: world[e2fsprogs] 
                  grub-efi (no such package): 
                        required by: world[grub-efi]
                    sfdisk (no such package):
                           required by: world[sfdisk]
                    alpine:~# y 
                    -ash: y: not found
                       alpine:~# ^[[20;11R```

**Comment by egandro** [comment]
I will do a full rewrite of this. I don't like the config file I am using at the moment.

**Comment by egandro** [comment]
@avto727 that bug looks like something in the downloader not working. Could be a firewall / other issue blocking qemu from downloading something - or the default URL where alpine does it's package management thing isn't working from your phone.

I probably should add something in the main script to check if we can connect to it.

**Comment by avto727** [comment]
I think you are right. Something with loading. Maybe a screenshot will help? I am ready to provide everything you need.

![image](https://user-images.githubusercontent.com/28927018/210437890-e22a90b0-b5aa-41f8-bb60-3a2f9616de07.png)

**Comment by avto727** [comment]
![image](https://user-images.githubusercontent.com/28927018/210443795-1bf094c2-a1c4-48e0-9601-0d4ab49d6b3c.png)

**Comment by egandro** [comment]
Nop.

Also cryistal clear where the error is.

It can'd download from alpinelinux.org - you need to fix something on your device. It's not the script.

**Comment by cmurtagh2010** [comment]
same error here. i can both ping and open in a browser the URL in question on the same device but the script still hangs

**Comment by egandro** [comment]
Probably then it's a DNS error in the Alpine image. I can't fix it - probably also the alpine image is too old.

**Comment by AjmalShajahan** [comment]
It worked for me last week, when i changed dns with the script,but did'nt when i tried qemu param

**Comment by DeicPro** [comment]
Same here.. I tried  many alpine versions and same results. IDK why this network bug.. i can't even ping to Google.. but this can be fixed in any way because vmConsole app (it's a Termux fork with qemu+alpine built-in) works perfectly.

**Comment by DeicPro** [comment]
Well the issue was the DNS settings, because doing ping to IPs instead domains is a check of that internet works. For some reason, eth0 router IP doesn't link correctly the real router IP, and then can't get the DNS of it... So the fix is as easy as set manually the IP of your router and/or optionally a DNS IP of your choice (for example Cloudflare DNS):

echo "nameserver 192.168.1.1
nameserver 1.1.1.1" > /etc/resolv.conf

**Comment by egandro** [comment]
I updated my script to the latest alpine version and fixed the DNS issues.

Please test!
