### ISSUE TITLE
bad URL script hangs

### ISSUE THREAD

**Issue by cmurtagh2010** [egandro/docker-qemu-arm#13]
* Starting busybox acpid ...
 [ ok ]
 * Starting busybox crond ...
 [ ok ]
wget: bad address 'mirrors.alpinelinux.org'
Updating repository indexes... ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.14/main: temporary error (try again later)
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.14/community: temporary error (try again later)
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.14/main: temporary error (try again later)
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.14/community: temporary error (try again later)
ERROR: unable to select packages:
  openssh (no such package):
    required by: world[openssh]
 * rc-update: service `sshd' does not exist
 * rc-service: service `sshd' does not exist
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.14/main: temporary error (try again later)
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.14/community: temporary error (try again later)
ERROR: unable to select packages:
  dosfstools (no such package):
    required by: world[dosfstools]
  e2fsprogs (no such package):
    required by: world[e2fsprogs]
  grub-efi (no such package):
    required by: world[grub-efi]
  sfdisk (no such package):
    required by: world[sfdisk]
alpine:~# y
-ash: y: not found
alpine:~# ^[[60;11R
^C

I was still able to ping google.com  and visiting http://dl-cdn.alpinelinux.org/alpine/v3.14/main/ ina browser works 

~ $ ping -c 1 google.com
PING google.com (142.250.217.142) 56(84) bytes of data.
64 bytes from lax31s19-in-f14.1e100.net (142.250.217.142): icmp_seq=1 ttl=112 time=31.2 ms

--- google.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 31.281/31.281/31.281/0.000 ms

**Comment by cmurtagh2010** [comment]
dupe of #12

**Comment by egandro** [comment]
Try ping the alpine url.
