### ISSUE TITLE
BdsDxe: failed to load Boot0002

### ISSUE THREAD

**Issue by PraveeshRamroop** [egandro/docker-qemu-arm#15]
When ./startqemu.sh I get the following error:  BdsDxe: failed to load Boot0001 "UEFI QEMU DVD-ROM QM00005 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x2,0xFFFF,0x0): Not Found
BdsDxe: failed to load Boot0002 "UEFI QEMU HARDDISK QM00001 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x0,0xFFFF,0x0): Not Found

What's the issue and how should I fix it?

**Comment by egandro** [comment]
I updated my script to the latest alpine version and fixed the DNS issues.

Please test!
