### ISSUE TITLE
Update the script 

### ISSUE THREAD

**Issue by AbdurRoufBusiness** [egandro/docker-qemu-arm#16]
Please update the script for latest alpine and docker

**Comment by AntonyZ89** [comment]
Hey! Check out my solution: https://github.com/AntonyZ89/docker-qemu-arm

Use the latest version of alpine and use docker from cli without having to enter the Alpine VM (but you still need to keep it running)

:smile:

**Comment by marcpinet** [comment]
~/alpine $ ./startqemu.sh
CANNOT LINK EXECUTABLE "qemu-system-x86_64": cannot locate symbol "g_once_init_enter_pointer" referenced by "/data/data/com.termux/files/usr/lib/libgstapp-1.0.so"...

**Comment by egandro** [comment]
> ~/alpine $ ./startqemu.sh CANNOT LINK EXECUTABLE "qemu-system-x86_64": cannot locate symbol "g_once_init_enter_pointer" referenced by "/data/data/com.termux/files/usr/lib/libgstapp-1.0.so"...

Something with your Termux. Reinstall it - update it - fix it. It looks like the qemu binary is not able to execute. 

If you can reproduce it on your phone, report it to Termux.

I highly suggest a clean install.
