### ISSUE TITLE
access docker containers gui

### ISSUE THREAD

**Issue by hdhnl** [egandro/docker-qemu-arm#2]
Τhe script works perfectly.
Τhanks a lot @egandro!
I start the virtual machine on termux, with the command:

`cd alpine && ./startqemu.sh`

I have created heimdall and portainer containers.
But, how can I connect to them with a graphical interface...
inside the browser of the host android device?
In which address?
I have tried the following addresses so far:
http://localhost:2222
http://<vm_eth0_ip>:9000
http://<vm_docker0_ip>:9000
http://127.0.0.1:9000 etc.
Thanks in advance.

**Comment by egandro** [comment]
Check the startqemu.sh command:

```
qemu-system-x86_64 -machine q35 -m 1024 -smp cpus=2 -cpu qemu64 \
  -drive if=pflash,format=raw,read-only,file=$PREFIX/share/qemu/edk2-x86_64-code.fd \
  -netdev user,id=n1,hostfwd=tcp::2222-:22 -device virtio-net,netdev=n1 \
  -nographic alpine.img
````

You can simply add exported ports to the hostfwd:

`hostfwd=tcp::3389-:3389,tcp:443::443,tcp:992::992,tcp:1194::1194,tcp:5555::5555,udp:1194::1194,udp:500::500,udp:4500::4500`

But carefull :) these are accessable from everywhere. I am not very familiar with the firewall of Android. You might be able to add some 127.0.0.1 prefix - but I don't know.

Docs are here: <https://readthedocs.org/projects/qemu/search/?q=hostfwd>

**Comment by egandro** [comment]
Well I guess you can also use ssh and add the -L portforwarding option then you have the 127.0.0.1 host only option.

**Comment by hdhnl** [comment]
Thanks a lot, i will try it!

**Comment by hdhnl** [comment]
Yes it works! Thanks a lot @egandro !
Here is my 'startqrmu.sh'
'#qemu-system-x86_64 -machine q35 -m 1024 -smp cpus=2 -cpu qemu64 \
 # -drive if=pflash,format=raw,read-only,file=$PREFIX/share/qemu/edk2-x86_64-code.fd \
  #-netdev user,id=n1,hostfwd=tcp::2222-:22 -device virtio-net,netdev=n1 \
  #-nographic alpine.img
qemu-system-x86_64 -machine q35 -m 1024 -smp cpus=2 -cpu qemu64 \
  -drive if=pflash,format=raw,read-only,file=$PREFIX/share/qemu/edk2-x86_64-code.fd \
  -netdev user,id=n1,hostfwd=tcp::2222-:22,hostfwd=tcp::5900-:5900,hostfwd=tcp::5901-:5901,hostfwd=tcp::8080-:8080,hostfwd=tcp::9000-:9000,hostfwd=tcp::8000-:8000,hostfwd=tcp::9090-:9090,hostfwd=tcp::4000-:4000,hostfwd=tcp::8001-:8001,hostfwd=tcp::19999-:19999,hostfwd=tcp::6000-:6000,hostfwd=tcp::7000-:7000,hostfwd=tcp::8081-:8081,hostfwd=tcp::1443-:1443,hostfwd=tcp::1080-:1080 -device virtio-net,netdev=n1 \
  -nographic alpine.img'
and screenshots from my containers:
![Screenshot_2021-07-03_17-43-23](https://user-images.githubusercontent.com/45640747/124360960-383f9300-dc35-11eb-9912-35d61014e941.png)
![Screenshot_2021-07-03_01-03-41](https://user-images.githubusercontent.com/45640747/124360967-4097ce00-dc35-11eb-9e73-6ac945857a89.png)
It will be possible to extend the vm's space?

**Comment by egandro** [comment]
@hdhnl this is sick on a phone :) but I love it.


-------------------------------------------------------

Edit the "installqemu.expect" and check line 32. 4GB is a 4GB file. 

You can try making this bigger - but not every phone might support that big files.

You can also add more "disks" via  qemu-img create and do fdisk/mk.ext4/fstab.

**Comment by hdhnl** [comment]
Yes, indeed @egandro !
Thanks a lot!
![Screenshot_2021-07-04_22-55-18](https://user-images.githubusercontent.com/45640747/124397884-5a134580-dd1b-11eb-89ea-32a3d7f13781.png)
