### ISSUE TITLE
Performance is a bit poor, can you help build an arm version of the virtual machine?

### ISSUE THREAD

**Issue by kingkongdog** [egandro/docker-qemu-arm#23]

**Comment by egandro** [comment]
Please read the qemu documentation.

Arm on Arm on an Android phone is also emulated. The emulator is slower then x86_64.

Please test this and if you have the proof that is wrong, I will do it.


It was already covered here: https://gist.github.com/oofnikj/e79aef095cd08756f7f26ed244355d62?permalink_comment_id=5057282#gistcomment-5057282
