### ISSUE TITLE
p30 error: CANNOT LINK EXECUTABLE

### ISSUE THREAD

**Issue by tensorgpu** [egandro/docker-qemu-arm#24]
Tried at Huawei P30

./startqemu.sh

CANNOT LINK EXECUTABLE "qemu-system-x86_64": cannot locate symbol "SSL_set_value_uint" referenced by "/data/data/com.termux/files/usr/lib/libcurl.so"...

**Comment by jinde98** [comment]
I had the same problem, changed the termux version and it was solved!

**Comment by egandro** [comment]
You might need to update the Termux packages.

**Comment by tensorgpu** [comment]
Thank you!!!
