### ISSUE TITLE
My installation is stop on  alpine system

### ISSUE THREAD

**Issue by jinde98** [egandro/docker-qemu-arm#25]
![image](https://github.com/user-attachments/assets/14581b81-2c13-4a79-b2e4-4e2614061db2)
I've been waiting for 2 hours for this to happen.

**Comment by egandro** [comment]
Can you open the URLs on your phone?

**Comment by jinde98** [comment]
Yes， I can open the ULRs on my phone.  And I switched to manually instal with answerfile and it worked!
