### ISSUE TITLE
Adding more space, and upgrading to Edge

### ISSUE THREAD

**Issue by hdhnl** [egandro/docker-qemu-arm#4]
Hello, I did an upgrade to the  to the rolling development version "edge", according to the [instructions](https://wiki.alpinelinux.org/wiki/Include:Upgrading_to_Edge).
I edited the file "installqemu.expect"  and increased the size to 6GB.
The error message that appears during the reboot is as follows:
```nt: /sys/fs/cgroup/pids: pids already mounted or mount point busy.
* Starting Docker Daemon ... [ ok ]
* Starting k3s ... [ ok ]
* Starting sshd ... [ ok ]
* Activating swap devices ... [ ok ]
* Loading zram module...
[ ok ]
* Swap->zram0
[ ok ]
* Mount zram1 /tmp
mke2fs 1.46.2 (28-Feb-2021)
mkfs.ext4: Invalid argument while setting blocksize; too small for device

zram-init:
mkfs.ext4 /dev/zram1 failed
[ !! ]

Welcome to Alpine Linux 3.14
Kernel 5.10.46-0-virt on an x86_64 (/dev/ttyS0)```

**Comment by hdhnl** [comment]
Keep in mind that I have already started a fresh installation and will increase the size again to 6GB.
 How can I "add more "disks" via qemu-img create and do fdisk/mk.ext4/fstab.'
Thanks in advance!

**Comment by egandro** [comment]
Yeah you might hit that 4gb limit of your device I was talking about.

You need to add a 2nd hardfile.

Untested (!)

`qemu-img create -f qcow2 2nd_drive.img 4G`

In startemu.sh you add this

`-nographic alpine.img 2nd_drive.img`

Inside qemu
```
dmesg
cat /proc/partition
```
^^^ this might be a /dev/hdb or /dev/sdb and then you can partition the drive etc.

**Comment by hdhnl** [comment]
Ok, let's assume we are not adding extra space.
How can we upgrade to Edge, without the following message:
```zram-init:
mkfs.ext4 /dev/zram1 failed
[ !! ]

Welcome to Alpine Linux 3.14
Kernel 5.10.46-0-virt on an x86_64 (/....```

The goal is to install lxd and podman!

**Comment by egandro** [comment]
Why do you make a fs on zram?

That is compressed ram... It makes no sense.

**Comment by hdhnl** [comment]
This is not my customization. It is probably a breakdown of the system due to the coexistence of current and edge repositories, after their processing, during the upgrade attempt.

**Comment by hdhnl** [comment]
The same error message after an proper upgrade on 3.14:
```
* Mounting local filesystems ... [ ok ]                * Configuring kernel parameters ... [ ok ]
 * Creating user login records ... [ ok ]               * Wiping /tmp directory ... [ ok ]
 * Setting hostname ... [ ok ]                          * Setting keymap ... [ ok ]
 * Starting networking ... *   lo ... [ ok ]
 *   eth0 ...udhcpc: started, v1.33.1                  udhcpc: sending discover
udhcpc: sending select for 10.0.2.15
udhcpc: lease of 10.0.2.15 obtained, lease time 86400
 [ ok ]                                                 * Starting busybox syslog ... [ ok ]
 * Initializing random number generator ... [ ok ]
 * Starting busybox acpid ... [ ok ]
 * Starting busybox crond ... [ ok ]
 * Mounting cgroup filesystem ... [ ok ]
 * Starting Docker Daemon ... [ ok ]
 * Starting sshd ... [ ok ]                             * Activating swap devices ... [ ok ]
 * Loading zram module...                               [ ok ]                                                 * Swap->zram0
 [ ok ]
 * Mount zram1 /tmp
mke2fs 1.46.2 (28-Feb-2021)                            mkfs.ext4: Invalid argument while setting blocksize; too small for device
zram-init:                                             mkfs.ext4 /dev/zram1 failed
 [ !! ]

Welcome to Alpine Linux 3.14                           Kernel 5.10.43-0-virt on an x86_64 (/dev/ttyS0)

alpine login:
```

**Comment by hdhnl** [comment]
After a fresh installation into Alpine 3.14
The message remains, but I do not notice any malfunction.  I have now installed, podman, pip3, podman-compose, and buildah.

**Comment by egandro** [comment]
I updated the installer to Alpine 3.14

I also fixed the zram issue.

**Comment by egandro** [comment]
You can increase the disk size.

`
$ mkdir alpine
$ curl -o config.env https://raw.githubusercontent.com/egandro/docker-qemu-arm/main/config.env
$ edit the config.env file
$ cd ..
$ curl -o termux-setup.sh https://raw.githubusercontent.com/egandro/docker-qemu-arm/master/termux-setup.sh && chmod 755 ./termux-setup.sh && ./termux-setup.sh
`

**Comment by hdhnl** [comment]
Thinking like a beginner I would suggest:
```$ mkdir alpine
$ cd alpine
$ curl -o config.env https://raw.githubusercontent.com/egandro/docker-qemu-arm/main/config.env
$ nano config.env 
$ cd ..
$ curl -o termux-setup.sh https://raw.githubusercontent.com/egandro/docker-qemu-arm/master/termux-setup.sh && chmod 755 ./termux-setup.sh && ./termux-setup.sh
```

**Comment by hdhnl** [comment]
>I updated the installer to Alpine 3.14.
>I also fixed the zram issue.

@egandro , it works!
![Screenshot_2021-07-11_10-22-10](https://user-images.githubusercontent.com/45640747/125186680-73912180-e234-11eb-9b3e-313c77dd9f13.png)
Image: My [Nginxproxymanager](https://nginxproxymanager.com/guide/#quick-setup), docker container!

**Comment by egandro** [comment]
> Thinking like a beginner I would suggest:

At this point, I see no need to explain super novice users "How to install Linux". You can easily create a 200 GB COW file and add it to qemu. Editing the config is of no use, since root pw depends on Alpine's constraints. Also the answerfile is also related to the Alpine ISO version. 

As we don't know what Alpine 3.20 will change, this is the best guess I can make at the current point.


I might split the downloader and the installer in future releases. That gives more freedom.

**Comment by hdhnl** [comment]
After the last changes you made to your script, @egandro, i have successfully installed (after upgrading to edge, the rolling distribution from 3.14), lxc containers.
![Screenshot_2021-07-22_01-32-13](https://user-images.githubusercontent.com/45640747/126571226-af8f8adb-b63a-47f8-a897-e59dc8bcf3fe.png)

**Comment by hdhnl** [comment]
The topic has been completed
