### ISSUE TITLE
./termux-setup.sh: 15: .: config.env: not found ?

### ISSUE THREAD

**Issue by Eric9453** [egandro/docker-qemu-arm#5]
Hi, when I install this on my Android Tablet. I met this error...

./termux-setup.sh: 15: .: config.env: not found

How can I fix it?

Thank you.

**Comment by egandro** [comment]
Use one of the scripts I provided for your platform e.g. this will download the config.env file

`$ curl -o termux-setup.sh https://raw.githubusercontent.com/egandro/docker-qemu-arm/master/termux-setup.sh && chmod 755 ./termux-setup.sh && ./termux-setup.sh`

**Comment by AjmalShajahan** [comment]
Try running with bash

**Comment by egandro** [comment]
I updated my script to the latest alpine version and fixed the DNS issues.

Please test!
