### ISSUE TITLE
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by rizkihrp** [egandro/docker-qemu-arm#8]
Hello, thanks for this superb script that make installation really easy, but I can't start hello-world, what's wrong?

![Screenshot_20211108-114406](https://user-images.githubusercontent.com/91236414/140686347-02d6657d-39fe-4071-ae40-5ba4e036323f.jpg)

**Comment by egandro** [comment]
I updated my script to the latest alpine version and fixed the DNS issues.

Please test!
